hmrc/emcs-tfe-frontend

app/uk/gov/hmrc/emcstfefrontend/config/AppConfig.scala
app/uk/gov/hmrc/emcstfefrontend/controllers/ViewMovementController.scala
app/uk/gov/hmrc/emcstfefrontend/views/ViewMovementPage.scala.html
conf/application.conf
conf/messages
conf/messages.cy
test/uk/gov/hmrc/emcstfefrontend/views/ViewMovementPageViewSpec.scala

App-Config-Base PR:
- https://github.com/hmrc/app-config-base/pull/8182

[ETFE-504] Add link to report a receipt (Placeholder only for now)

---

app/uk/gov/hmrc/emcstfefrontend/views/templates/Layout.scala.html
conf/application.conf
project/AppDependencies.scala
project/plugins.sbt

**Note:**
The directives don't need to be defined. As we can use the directives from bootstrap for now, as we don't have anything that deviates from the default.

[ETFE-1152] Enable CSP and Nonce pattern & header

---

app/uk/gov/hmrc/emcstfefrontend/config/AppConfig.scala
test/uk/gov/hmrc/emcstfefrontend/views/ViewMovementPageViewSpec.scala

To be merged after https://github.com/hmrc/emcs-tfe-report-a-receipt-frontend/pull/160

[ETFE-1498] point to new report receipt index page

---

app/uk/gov/hmrc/emcstfefrontend/models/common/AddressModel.scala
app/uk/gov/hmrc/emcstfefrontend/models/common/TraderModel.scala
app/uk/gov/hmrc/emcstfefrontend/models/response/emcsTfe/GetMovementResponse.scala
test/uk/gov/hmrc/emcstfefrontend/connectors/emcsTfe/GetMovementConnectorSpec.scala
test/uk/gov/hmrc/emcstfefrontend/controllers/ViewMovementControllerSpec.scala
test/uk/gov/hmrc/emcstfefrontend/models/GetMovementResponseSpec.scala
test/uk/gov/hmrc/emcstfefrontend/views/ViewMovementPageViewSpec.scala

Dependent on:
- https://github.com/hmrc/emcs-tfe/pull/60

[ETFE-1568] Minor refactor to models

---

app/uk/gov/hmrc/emcstfefrontend/config/AppConfig.scala
app/uk/gov/hmrc/emcstfefrontend/views/ViewMovementPage.scala.html
conf/application.conf
conf/messages
conf/messages.cy
test/uk/gov/hmrc/emcstfefrontend/views/ViewMovementPageViewSpec.scala

[ETFE-explain-shortage-excess-link] added link to esoe

---

app/uk/gov/hmrc/emcstfefrontend/config/AppConfig.scala
app/uk/gov/hmrc/emcstfefrontend/views/ErrorTemplate.scala.html
app/uk/gov/hmrc/emcstfefrontend/views/ExciseNumbersPage.scala.html
app/uk/gov/hmrc/emcstfefrontend/views/ViewMovementListPage.scala.html
app/uk/gov/hmrc/emcstfefrontend/views/components/p.scala.html
conf/application.conf
conf/logback-test.xml
conf/logback.xml
conf/messages
test/uk/gov/hmrc/emcstfefrontend/views/components/PSpec.scala

Related PR: https://github.com/hmrc/app-config-base/pull/9318

[ETFE-CAM] add link to CAM

---

conf/application.conf
conf/prod.routes
it/uk/gov/hmrc/emcstfefrontend/support/IntegrationBaseSpec.scala
project/plugins.sbt
test/uk/gov/hmrc/emcstfefrontend/controllers/predicates/AuthActionSpec.scala
test/uk/gov/hmrc/emcstfefrontend/controllers/predicates/SelectExciseNumberAuthActionSpec.scala

See also https://github.com/hmrc/mdtp-frontend-routes/pull/3101

[ETFE-2795] update emcs-tfe-frontend base URL

---

app/controllers/ViewMovementController.scala
app/views/components/link.scala.html
app/views/viewMovement/ViewMovementPage.scala.html
conf/messages
test-utils/fixtures/messages/ViewMovementMessages.scala
test/models/common/DestinationTypeSpec.scala
test/views/ViewMovementPageViewSpec.scala

Depends on https://github.com/hmrc/emcs-tfe-frontend/pull/43 being merged 1st

ETFE-2834 MOV02 - movement-overview (Action links)

---

app/connectors/emcsTfe/GetMovementHistoryEventsConnector.scala
app/controllers/ViewMovementController.scala
app/models/response/ErrorResponse.scala
app/models/response/emcsTfe/GetMovementResponse.scala
app/models/response/emcsTfe/getMovementHistoryEvents/GetMovementHistoryEventsResponse.scala
app/models/response/emcsTfe/getMovementHistoryEvents/MovementHistoryEvent.scala
app/services/GetMovementHistoryEventsService.scala
app/services/GetMovementService.scala
app/viewmodels/TimelineEvent.scala
app/viewmodels/helpers/TimelineHelper.scala
app/views/ViewUtils.scala
app/views/components/timeline.scala.html
app/views/viewMovement/ViewMovementPage.scala.html
conf/messages
it/ViewMovementIntegrationSpec.scala
it/connectors/GetMovementHistoryEventsConnectorISpec.scala
test-utils/fixtures/GetMovementHistoryEventsResponseFixtures.scala
test-utils/fixtures/GetMovementResponseFixtures.scala
test/connectors/emcsTfe/GetMovementHistoryEventsConnectorSpec.scala
test/controllers/ViewMovementControllerSpec.scala
test/mocks/connectors/MockGetMovementHistoryEventsConnector.scala
test/mocks/services/MockGetMovementHistoryEventsService.scala
test/services/GetMovementHistoryEventsServiceSpec.scala
test/services/GetMovementServiceSpec.scala
test/viewmodels/helpers/TimelineHelperSpec.scala
test/views/ViewMovementPageViewSpec.scala

Requires https://github.com/hmrc/emcs-tfe-stub/pull/31

ETFE-2865 MOV02 Event history

---

app/models/common/AcceptMovement.scala
app/models/response/emcsTfe/reportOfReceipt/ReportOfReceiptModel.scala
app/viewmodels/helpers/ViewMovementHelper.scala
app/viewmodels/helpers/ViewMovementItemsHelper.scala
conf/messages
test-utils/fixtures/GetMovementResponseFixtures.scala
test-utils/fixtures/ReportOfReceiptFixtures.scala
test-utils/fixtures/messages/ViewMovementMessages.scala
test/viewmodels/helpers/ViewMovementHelperSpec.scala
test/viewmodels/helpers/ViewMovementItemsHelperSpec.scala

Dependent on following being reviewed and merged first. Then this can be rebased from `main`:
- #46
**Update**:
This has been rebased now from main.

[ETFE-2882] Add the `receipt` column to the Items movment view

---

app/assets/stylesheets/application.scss
app/controllers/ViewAllMovementsController.scala
app/forms/ViewAllMovementsFormProvider.scala
app/models/MovementListSearchOptions.scala
app/models/MovementSearchSelectOption.scala
app/viewmodels/govuk/ButtonFluency.scala
app/views/viewAllMovements/MovementsList.scala.html
app/views/viewAllMovements/ViewAllMovements.scala.html
conf/messages
test-utils/fixtures/messages/ViewAllMovementsMessages.scala
test/controllers/ViewAllMovementsControllerSpec.scala
test/forms/ViewAllMovementsFormProviderSpec.scala
test/models/MovementListSearchOptionsSpec.scala
test/models/MovementSearchSelectOptionSpec.scala
test/viewmodels/helpers/MovementPaginationHelperSpec.scala
test/views/ViewAllMovementsViewSpec.scala
test/views/ViewMovementPageViewSpec.scala

To simplify and replace #49 - which can be closed if this PR contains everything from the original branch. This was to simplify rebasing.

[ETFE-2789] - Added search functionality (plus form guards) for MOV01

---

conf/messages
test-utils/fixtures/MessagesFixtures.scala
test/views/messages/ViewMessageSpec.scala

Dependant on https://github.com/hmrc/emcs-tfe-frontend/pull/69 being merged first.

ETFE-3260 Msg for IE819 Alert or rejection submitted successfully

---

app/viewmodels/helpers/messages/ViewMessageHelper.scala
conf/messages
test-utils/fixtures/MessagesFixtures.scala
test/views/messages/ViewMessageSpec.scala

Depends on https://github.com/hmrc/emcs-tfe-frontend/pull/71

ETFE-3302 Msg for IE810 Cancellation received

---

app/viewmodels/helpers/messages/ViewMessageHelper.scala
conf/messages
test-utils/fixtures/MessagesFixtures.scala
test/views/messages/ViewMessageSpec.scala

depends on https://github.com/hmrc/emcs-tfe-frontend/pull/82

ETFE-3334 Msg for IE839 Customs rejection of movement for export

---

app/viewmodels/helpers/messages/ViewMessageHelper.scala
conf/messages
test-utils/fixtures/MessagesFixtures.scala
test-utils/fixtures/messages/ViewMessageMessages.scala
test/viewmodels/helpers/messages/ViewMessageHelperSpec.scala
test/views/messages/ViewMessageSpec.scala

~Raising as draft due to stub data needed~

[ETFE-3348] - Added IE837 in error page

---

app/viewmodels/helpers/messages/ViewMessageHelper.scala
conf/messages
test-utils/fixtures/MessagesFixtures.scala
test-utils/fixtures/messages/ViewMessageMessages.scala
test/viewmodels/helpers/messages/ViewMessageHelperSpec.scala
test/views/messages/ViewMessageSpec.scala

[ETFE-3351] - Added IE871 in error page

---

app/viewmodels/helpers/messages/ViewMessageHelper.scala
test/viewmodels/helpers/messages/ViewMessageHelperSpec.scala
test/views/messages/ViewMessageSpec.scala

To be merged with https://github.com/hmrc/emcs-tfe-journey-tests/pull/397

[ETFE-3473] - Add IDs to 704 links

---

app/models/response/emcsTfe/messages/submissionFailure/GetSubmissionFailureMessageResponse.scala
app/viewmodels/helpers/messages/ViewMessageHelper.scala
conf/messages
test-utils/fixtures/GetSubmissionFailureMessageFixtures.scala
test-utils/fixtures/messages/ViewMessageMessages.scala
test/viewmodels/helpers/messages/ViewMessageHelperSpec.scala
test/views/messages/ViewMessageSpec.scala

Requires BE PR: https://github.com/hmrc/emcs-tfe/pull/137

[ETFE-3551] Updated based on latest copy deck changes

---

app/config/AppConfig.scala
app/controllers/helpers/BetaChecks.scala
app/controllers/predicates/AuthActionHelper.scala
app/controllers/prevalidateTrader/PrevalidateAddToListController.scala
app/controllers/prevalidateTrader/PrevalidateConsigneeTraderIdentificationController.scala
app/controllers/prevalidateTrader/PrevalidateExciseProductCodeController.scala
app/controllers/prevalidateTrader/PrevalidateRemoveExciseProductCodeController.scala
app/controllers/prevalidateTrader/PrevalidateTraderStartController.scala
test/controllers/prevalidateTrader/ExciseProductCodeControllerSpec.scala
test/controllers/prevalidateTrader/PrevalidateAddToListControllerSpec.scala
test/controllers/prevalidateTrader/PrevalidateConsigneeTraderIdentificationControllerSpec.scala
test/controllers/prevalidateTrader/PrevalidateRemoveExciseProductCodeControllerSpec.scala
test/controllers/prevalidateTrader/PrevalidateTraderStartControllerSpec.scala

Requires https://github.com/hmrc/emcs-tfe-frontend/pull/118

ETFE-3625 Private beta routing for pre validate trader

---

app/connectors/emcsTfe/EmcsTfeHttpParser.scala
app/connectors/emcsTfe/PrevalidateTraderConnector.scala
app/controllers/cod/ChangeOfDestinationController.scala
app/controllers/drafts/DraftsController.scala
app/controllers/prevalidateTrader/PrevalidateTraderResultsController.scala
app/models/requests/PrevalidateTraderRequest.scala
app/models/response/ErrorResponse.scala
app/models/response/emcsTfe/prevalidateTrader/ExciseTraderValidationResponse.scala
app/navigation/PrevalidateTraderNavigator.scala
app/services/PrevalidateTraderService.scala
app/viewmodels/helpers/PrevalidateTraderResultsHelper.scala
app/views/prevalidateTrader/PrevalidateTraderResultsView.scala.html
conf/messages
conf/prevalidateTrader.routes
it/connectors/PrevalidateTraderConnectorISpec.scala
test-utils/fixtures/PrevalidateTraderFixtures.scala
test-utils/fixtures/messages/prevalidateTrader/PrevalidateTraderResultsMessages.scala
test/connectors/emcsTfe/PrevalidateTraderConnectorSpec.scala
test/controllers/prevalidateTrader/PrevalidateExciseProductCodeControllerSpec.scala
test/controllers/prevalidateTrader/PrevalidateTraderResultsControllerSpec.scala
test/mocks/connectors/MockPrevalidateTraderConnector.scala
test/mocks/services/MockPrevalidateTraderService.scala
test/navigation/PrevalidateTraderNavigatorSpec.scala
test/services/PrevalidateTraderServiceSpec.scala
test/viewmodels/helpers/PrevalidateTraderResultsHelperSpec.scala
test/views/BaseSelectors.scala
test/views/prevalidateTrader/PrevalidateTraderResultsViewSpec.scala

With connectivity to backend to submit and handle result

[ETFE-3611] - Pre-validate trader results page

---

app/connectors/emcsTfe/GetMovementConnector.scala
app/controllers/ItemDetailsController.scala
app/controllers/ViewMovementController.scala
app/controllers/messages/ViewMessageController.scala
app/services/GetMovementService.scala
it/connectors/GetMovementConnectorISpec.scala
project/plugins.sbt
test/connectors/emcsTfe/GetMovementConnectorSpec.scala
test/controllers/ItemDetailsControllerSpec.scala
test/controllers/ViewMovementControllerSpec.scala
test/controllers/messages/ViewMessageControllerSpec.scala
test/mocks/connectors/MockEmcsTfeConnector.scala
test/mocks/services/MockGetMovementService.scala
test/services/GetMovementServiceSpec.scala

https://github.com/hmrc/emcs-tfe-stub/pull/97

ETFE-3620 Retrieve the latest movement the logged-in user is allowed to see

---

app/assets/stylesheets/application.scss
app/views/viewAllDrafts/DraftMovementsList.scala.html
app/views/viewAllDrafts/ViewAllDraftMovementsView.scala.html
app/views/viewAllMovements/MovementsList.scala.html
app/views/viewAllMovements/ViewAllMovementsView.scala.html
app/views/viewMovement/ViewMovementView.scala.html

[ETFE-3882] - Remove min-width from select option in filter panel and some minor visual formatting

---

app/controllers/events/ViewEventController.scala
app/viewmodels/helpers/events/EventsHelper.scala
app/viewmodels/helpers/events/MovementEventHelper.scala
app/views/AccountHomeView.scala.html
app/views/ErrorTemplate.scala.html
app/views/auth/errors/DutyPaidUserUnauthorisedAccessView.scala.html
app/views/messages/DeleteMessageView.scala.html
build.sbt
conf/events.routes
conf/messages
test-utils/fixtures/GetMovementHistoryEventsResponseFixtures.scala
test-utils/fixtures/GetMovementResponseFixtures.scala
test-utils/fixtures/GetSubmissionFailureMessageFixtures.scala
test-utils/fixtures/events/MovementEventMessages.scala
test/controllers/events/ViewEventControllerSpec.scala
test/controllers/messages/DeleteMessageControllerSpec.scala
test/forms/ViewAllDraftMovementsFormProviderSpec.scala
test/forms/ViewAllMovementsFormProviderSpec.scala
test/models/MovementListSearchOptionsSpec.scala
test/models/draftMovements/GetDraftMovementsSearchOptionsSpec.scala
test/services/GetWineOperationsServiceSpec.scala
test/viewmodels/helpers/ViewMovementDeliveryHelperSpec.scala
test/viewmodels/helpers/ViewMovementGuarantorHelperSpec.scala
test/viewmodels/helpers/events/EventsHelperSpec.scala
test/viewmodels/helpers/events/MovementEventHelperSpec.scala
test/viewmodels/helpers/messages/ViewMessageHelperSpec.scala
test/views/events/HistoryEventViewSpec.scala
test/views/messages/ViewMessageViewSpec.scala

Cleans up trailing commas from files

[ETFE-4105] - Add IE905 event history page

---

app/models/common/GuarantorType.scala
app/viewmodels/helpers/ViewMovementGuarantorHelper.scala
conf/messages
test/viewmodels/helpers/ViewMovementGuarantorHelperSpec.scala

Requires https://github.com/hmrc/emcs-tfe-stub/pull/122

ETFE-4177 MOV02 Guarantor tab to support joint guarantors

---

app/config/AppConfig.scala
app/featureswitch/core/config/FeatureSwitchingModule.scala
app/models/common/RoleType.scala
app/viewmodels/helpers/ViewMovementHelper.scala
app/views/AccountHomeView.scala.html
app/views/components/navigation_bar.scala.html
conf/application.conf
test/views/AccountHomeViewSpec.scala
test/views/components/NavigationBarSpec.scala

Related:
- https://github.com/hmrc/app-config-qa/pull/22648
- https://github.com/hmrc/app-config-production/pull/22689

[ETFE-4181] add feature switch to block XIPC from coming into CaM

---

app/viewmodels/helpers/ViewMovementActionsHelper.scala
app/views/messages/ViewAllMessagesView.scala.html
conf/messages
test-utils/fixtures/messages/ViewAllMessagesMessages.scala
test/views/messages/ViewAllMessagesViewSpec.scala

[ETFE-3830] - Add content when the user has no messages

---

app/forms/ViewAllDraftMovementsFormProvider.scala
app/forms/ViewAllMovementsFormProvider.scala
app/forms/package.scala
app/models/MovementListSearchOptions.scala
app/models/MovementSortingSelectOption.scala
test/controllers/ViewAllMovementsControllerSpec.scala
test/controllers/drafts/ViewAllDraftMovementsControllerSpec.scala
test/forms/ViewAllDraftMovementsFormProviderSpec.scala
test/forms/ViewAllMovementsFormProviderSpec.scala
test/models/MovementListSearchOptionsSpec.scala

- **[ETFE-4265] WIP - allow spaces etc in movement search field**
- **[ETFE-4265] allow spaces to search on view movements and view drafts pages**

[ETFE-4265] allow spaces to search on view movements and view drafts pages

---

app/forms/package.scala
app/models/NavigationBannerInfo.scala
app/models/movementScenario/MovementScenario.scala
app/views/AccountHomeView.scala.html
app/views/ItemDetailsView.scala.html
app/views/components/navigation_bar.scala.html
app/views/events/HistoryEventView.scala.html
app/views/messages/DeleteMessageView.scala.html
app/views/messages/ViewAllMessagesView.scala.html
app/views/messages/ViewMessageView.scala.html
app/views/prevalidateTrader/PrevalidateAddToListView.scala.html
app/views/prevalidateTrader/PrevalidateConsigneeTraderIdentificationView.scala.html
app/views/prevalidateTrader/PrevalidateExciseProductCodeView.scala.html
app/views/prevalidateTrader/PrevalidateTraderRemoveExciseProductCodeView.scala.html
app/views/prevalidateTrader/PrevalidateTraderResultsView.scala.html
app/views/prevalidateTrader/PrevalidateTraderStartView.scala.html
app/views/viewAllDrafts/ViewAllDraftMovementsView.scala.html
app/views/viewAllMovements/ViewAllMovementsView.scala.html
app/views/viewMovement/ViewMovementView.scala.html
test/forms/FormSpec.scala
test/forms/packageSpec.scala
test/views/components/NavigationBarSpec.scala

- Trim whitespace before submitting on draft & movement search pages
- Correct prevalidate active section on nav bar (none)

[ETFE-4265] demo comments

---

app/services/GetMovementService.scala
app/utils/Logging.scala
app/viewmodels/helpers/ViewMovementHelper.scala
test/services/GetMovementServiceSpec.scala
test/viewmodels/helpers/ViewMovementHelperSpec.scala

Alert Config:
- https://github.com/hmrc/alert-config/pull/3747

[ETFE-4330] Make movementType and history optional

---

app/controllers/proxyRedirect/ProxyRedirectController.scala
conf/prod.routes
conf/redirect.routes
it/ProxyRedirectControllerIntegrationSpec.scala

QA change:
- https://github.com/hmrc/mdtp-frontend-routes/pull/3218

[ETFE-4341] Add proxy route for redirect from Legacy route

---

app/config/AppConfig.scala
app/config/EnrolmentKeys.scala
app/config/Module.scala
app/controllers/partials/NavBarPartialController.scala
app/models/messages/MessageStatisticsCache.scala
app/repositories/MessageStatisticsRepository.scala
app/services/GetMessageStatisticsService.scala
app/views/components/navigation_bar.scala.html
conf/application.conf
conf/partials.routes
conf/prod.routes
it/AccountHomeIntegrationSpec.scala
it/NavBarPartialIntegrationSpec.scala
it/support/IntegrationBaseSpec.scala
test/mocks/repositories/MockMessageStatisticsRepository.scala
test/repositories/MessageStatisticsRepositorySpec.scala
test/services/GetMessageStatisticsServiceSpec.scala

- https://github.com/hmrc/app-config-production/pull/22911

[ETFE-4363] Add partial to return NavBar, cache for MessageStats and Graceful message stats handling

---

app/services/GetMessageStatisticsService.scala
test/services/GetMessageStatisticsServiceSpec.scala

Small PR, just to ensure that when viewing the messages page the notice count is always updated to keep them in sync with the body content.

[ETFE-ForceFetchNewMessagesStats] Always call core for Message stats when on Messages page

---

app/config/AppConfig.scala
app/controllers/draftTemplates/ViewAllTemplatesController.scala
app/controllers/predicates/AuthActionHelper.scala
app/featureswitch/core/config/FeatureSwitchingModule.scala
app/models/PageSection.scala
app/models/draftTemplates/Template.scala
app/views/AccountHomeView.scala.html
app/views/ViewAllTemplatesView.scala.html
app/views/components/navigation_bar.scala.html
conf/app.routes
conf/application.conf
conf/messages
test-utils/fixtures/messages/NavigationBarMessages.scala
test-utils/fixtures/messages/ViewAllTemplatesMessages.scala
test/controllers/draftTemplates/ViewAllTemplatesControllerSpec.scala
test/controllers/predicates/AuthActionSpec.scala
test/views/AccountHomeViewSpec.scala
test/views/ViewAllTemplatesViewSpec.scala
test/views/components/NavigationBarSpec.scala

Related PR(s):
- https://github.com/hmrc/app-config-production/pull/23260
- https://github.com/hmrc/emcs-tfe-journey-tests/pull/542

[ETFE-4495] Add templates link and placeholder page

---

app/assets/stylesheets/application.scss

ETFE-4463 CSS added for service name

---

app/views/components/navigation_bar.scala.html
test/views/AccountHomeViewSpec.scala

[ETFE-3851] Updated the Account Home header to match pattern

---

app/assets/stylesheets/application.scss
app/viewmodels/ViewAllMovementsTableHelper.scala
app/viewmodels/draftMovements/ViewAllDraftMovementsTableHelper.scala
app/views/viewAllDrafts/DraftMovementsTableRowContentStatus.scala.html
app/views/viewMovement/PrintMovementView.scala.html
app/views/viewMovement/ViewMovementView.scala.html
test/viewmodels/ViewAllMovementsTableHelperSpec.scala
test/views/viewAllDrafts/ViewAllDraftMovementsViewSpec.scala

[ETFE-4621] Add break-word to the ARC and fix table width via colspan to enforce word-break
